create table students(
	student_id int generated by default as identity
	(start with 40000 increment by 2),
	first_name varchar(25) not null, 
	middle_name varchar(25),
	last_name varchar(25) not null,
	email varchar(50) unique not null,
	date_of_birth date not null,
	date_enrolled date not null,
	primary key(student_id)
);

create table instructors(
	instructor_id int not null,
	first_name varchar(25) not null,
	middle_name varchar(25), 
	last_name varchar(25) not null,
	email varchar(50) unique not null, 
	education_title varchar(20) not null,
	primary key(instructor_id)
);

create table courses(
	course_id int generated by default as identity
	(start with 100 increment by 10),
	course_name varchar(50) unique not null,
	description varchar(150),
	credits int not null,
	instructor_id int not null,
	primary key(course_id),
	constraint instructor_id
		foreign key (instructor_id) 
		references instructors(instructor_id)
		on delete cascade
);

create table enrollments (
	enrolment_id int generated by default as identity
	(start with 20000 increment by 4),
	student_id int not null,
	course_id int not null,
	primary key(enrolment_id),
	constraint student_id
		foreign key (student_id) 
		references students(student_id)
		on delete cascade,	
	constraint course_id
		foreign key (course_id) 
		references courses(course_id)
		on delete cascade,
	date_enrolled date not null
);


