-- Please execute the whole code at once ;-)

CREATE TABLE students(
     student_id INT GENERATED BY DEFAULT AS IDENTITY
         (START WITH 40000 INCREMENT BY 2),
     first_name VARCHAR(25) NOT NULL,
     middle_name VARCHAR(25),
     last_name VARCHAR(25) NOT NULL,
     email VARCHAR(50) UNIQUE NOT NULL,
     date_of_birth DATE NOT NULL,
     PRIMARY KEY(student_id)
);

CREATE TABLE instructors(
    instructor_id INT NOT NULL,
    first_name VARCHAR(25) NOT NULL,
    middle_name VARCHAR(25),
    last_name VARCHAR(25) NOT NULL,
    email VARCHAR(50) UNIQUE NOT NULL,
    education_title VARCHAR(20) NOT NULL,
    PRIMARY KEY(instructor_id)
);

CREATE TABLE courses(
    course_id INT GENERATED BY DEFAULT AS IDENTITY
        (START WITH 100 INCREMENT BY 10),
    course_name VARCHAR(50) UNIQUE NOT NULL,
    description VARCHAR(150),
    credits INT NOT NULL,
    instructor_id INT NOT NULL,
    PRIMARY KEY(course_id),
    CONSTRAINT instructor_id
        FOREIGN KEY (instructor_id)
            REFERENCES instructors(instructor_id)
            ON DELETE CASCADE
);

CREATE TABLE enrollments (
     enrolment_id INT GENERATED BY DEFAULT AS IDENTITY
         (START WITH 20000 INCREMENT BY 4),
     student_id INT NOT NULL,
     course_id INT NOT NULL,
     PRIMARY KEY(enrolment_id),
     CONSTRAINT student_id
         FOREIGN KEY (student_id)
             REFERENCES students(student_id)
             ON DELETE CASCADE,
     CONSTRAINT course_id
         FOREIGN KEY (course_id)
             REFERENCES courses(course_id)
             ON DELETE CASCADE,
     date_enrolled DATE NOT NULL
);
